disabled_rules:
  - line_length
  - force_try
  - force_cast
  - identifier_name
  - todo
opt_in_rules:
  - overridden_super_call
  - prohibited_super_call
  - discarded_notification_center_observer
  - dynamic_inline
  - first_where
  - valid_ibinspectable
  - weak_delegate
  - file_length
included: 
 - TheMovieDB
 - TheMovieDBTests
 #- TheMovieDBUITests
excluded:
  - Pods
identifier_name:
  max_length:
    warning: 45
    error: 60
  min_length:
    warning: 1
force_try:
  severity: warning
function_body_length:
  warning: 100
  error: 200
function_parameter_count:
  warning: 6
  error: 7
line_length: 160
reporter: "checkstyle"
