language: objective-c
osx_image: xcode10.1

cache:
  directories:
  - "$HOME/.vendor/bundle/"
  - Pods

if: (branch = master AND type = push) OR (head_branch != master AND type = pull_request)

before_install:
- export TRAVIS_COMMIT_MSG=\"$(git log --format=%B --no-merges -n 1)\"
- export TRAVIS_CHANGELOG_MESSAGE=$(sed -n -e "1,/#/p" CHANGELOG.md | grep -v "^#")
- gem update --system
- gem install bundler

install:
- bundle install --jobs=3 --retry=3
- pod install --repo-update

stages:
- name: run tests

jobs:
  include:
  - stage: run tests
    script: fastlane unit_test