language: objective-c
osx_image: xcode10.1

cache:
  directories:
  - "$HOME/.vendor/bundle/"
  - Pods
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

if: (branch = master AND type = push) OR (head_branch != master AND type = pull_request)

before_install:
- export TRAVIS_COMMIT_MSG=\"$(git log --format=%B --no-merges -n 1)\"
- export TRAVIS_CHANGELOG_MESSAGE=$(sed -n -e "1,/#/p" CHANGELOG.md | grep -v "^#")

install:
- bundle install --jobs=3 --retry=3 --path=$HOME/.vendor/bundle/
- bundle exec pod install --repo-update

stages:
- name: run tests
- name: upload ipa to app store

jobs:
  include:
  - stage: run tests
    script: "./scripts/run_unit_tests.sh unit"
  - script: "./scripts/run_unit_tests.sh ui"
  - stage: upload ipa to app store
    script: bundle exec fastlane beta